---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: Australia/Brisbane
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title: ChipsnCode
keywords: electronics, code, arduino, raspberry pi, open source, DIY, maker, hacker
description: Pushing the boundaries of what I can do, one line of code at a time
source_link:
favicon: rocket
touch_icon: apple
google_analytics_key:


### template colors, used site-wide via css ###
colors:
  black:
    light: '#303030'
    dark: '#111111'
  white:
    light: '#f5f5f5'
    dark: '#f8f8f8'
  red:
    light: '#DA4C47'
    dark: '#CC4A45'
  blue:
    light: '#3c9eec'
    dark: '#49a7e9'
  green:
    light: '#a3d832'
    dark: '#9bcf2f'
  purple:
    light: '#c869bf'
    dark: '#c869bf'
  orange:
    light: '#faaf22'
    dark: '#fab125'
  turquoise:
    light: '#0fbfcf'
    dark: '#0fbfcf'
  yellow:
    light: '#ffff66'
    dark: '#cccc00'
  pink:
    light: '#ffcce5'
    dark: '#cc0066'
  wood:
    light: '#fff5ee'
    dark: '#a0522d'
  cyan:
    light: '#e0ffff'
    dark: '#008b8b'
  lavender:
    light: '#fff0f5'
    dark: '#e6e6fa'
azureivory:
    light: '#f0ffff'
    dark: 'fffff0'
seagreen:
    light: '#20b2aa'
    dark: '#2e8b57'
